let $lang = {};
$lang.ko = {
	"check_available" : "사용이 가능합니다.",
	"user_id_vaildation" : "영문시작, 영문+숫자 조합 6~20자리",
	"user_email_vaildation" : "유효한 이메일 형식",
	"user_email_not_vaildation" : "유효하지 않은 이메일 형식입니다.",
	"user_pw_vaildation" : "문자, 숫자 1개이상 포함, 6~24자리",
	"user_pw_match" : "비밀번호 일치",
	"user_pw_not_match" : "비밀번호가 일치하지 않습니다.",
	"user_id_duplicate" : "아이디 중복확인",
	"user_id_duplicate_check" : "아이디 중복확인이 필요합니다.",
	"user_email_duplicate" : "이메일 중복확인",
	"user_email_duplicate_check" : "이메일주소 중복확인이 필요합니다.",
	"already_use_user_id" : "이미 사용중인 아이디입니다.",
	"already_use_user_email" : "이미 사용중인 이메일 주소입니다.",
	"required" : "\'%s\'은(는) 필수 입력 사항입니다.",
	"required_check" : "\'%s\'은(는) 필수 선택 사항입니다.",
	"required_id" : "아이디를 입력하세요.",
	"required_email" : "이메일 주소를 입력하세요.",
	"required_pw" : "비밀번호를 입력하세요.",
	"required_mobile" : "휴대전화번호 11자리를 입력하여 주십시오.",
	"not_allowed_file_format" : "파일 형식이 올바르지 않습니다.",
	"not_allowed_file_size" : "파일 용량을 초과하였습니다.",
	"not_match_captcha" : "보안문자가 일치하지 않습니다.",
	"invalid_email" : "올바르지 않은 이메일 형식입니다.",
	"agree_term" : "이용약관에 동의하여 주십시오.",
	"agree_privacy" : "개인정보취급 방침에 동의하여 주십시오.",
};
$lang.en = {
	"check_available" : "사용이 가능합니다.",
	"user_id_vaildation" : "",
	"user_email_vaildation" : "",
	"user_email_not_vaildation" : "",
	"user_pw_vaildation" : "문자, 숫자 1개이상 포함, 6~24자리",
	"user_pw_match" : "비밀번호 일치",
	"user_pw_not_match" : "비밀번호가 일치하지 않습니다.",
	"user_id_duplicate" : "",
	"user_id_duplicate_check" : "",
	"user_email_duplicate" : "이메일 중복확인",
	"user_email_duplicate_check" : "",
	"already_use_user_id" : "",
	"already_use_user_email" : "",
	"required" : "",
	"required_check" : "",
	"required_id" : "",
	"required_email" : "",
	"required_pw" : "",
	"required_mobile" : "",
	"not_allowed_file_format" : "",
	"not_allowed_file_size" : "",
	"not_match_captcha" : "\'보안문자\'가 일치하지 않습니다.",
	"invalid_email" : "올바르지 않은 \'이메일 형식\'입니다.",
	"agree_term" : "",
	"agree_privacy" : "",
};
$lang.ja = {
	"check_available" : "",
	"user_id_vaildation" : "",
	"user_email_vaildation" : "",
	"user_email_not_vaildation" : "",
	"user_pw_vaildation" : "문자, 숫자 1개이상 포함, 6~24자리",
	"user_pw_match" : "비밀번호 일치",
	"user_pw_not_match" : "비밀번호가 일치하지 않습니다.",
	"user_id_duplicate" : "",
	"user_id_duplicate_check" : "",
	"user_email_duplicate" : "이메일 중복확인",
	"user_email_duplicate_check" : "",
	"already_use_user_id" : "",
	"already_use_user_email" : "",
	"required" : "",
	"required_check" : "",
	"required_id" : "",
	"required_email" : "",
	"required_pw" : "",
	"required_mobile" : "",
	"not_allowed_file_format" : "",
	"not_allowed_file_size" : "",
	"not_match_captcha" : "1",
	"invalid_email" : "1",
	"agree_term" : "",
	"agree_privacy" : "",
};
$lang.fr = {
	"check_available" : "",
	"user_id_vaildation" : "",
	"user_email_vaildation" : "",
	"user_email_not_vaildation" : "",
	"user_pw_vaildation" : "",
	"user_pw_match" : "",
	"user_pw_not_match" : "",
	"user_id_duplicate" : "",
	"user_id_duplicate_check" : "",
	"user_email_duplicate" : "",
	"user_email_duplicate_check" : "",
	"already_use_user_id" : "",
	"already_use_user_email" : "",
	"required" : "",
	"required_check" : "",
	"required_id" : "",
	"required_email" : "",
	"required_pw" : "",
	"required_mobile" : "",
	"not_allowed_file_format" : "",
	"not_allowed_file_size" : "",
	"not_match_captcha" : "",
	"invalid_email" : "",
	"agree_term" : "",
	"agree_privacy" : "",
};
